"use strict";
var assert = require("node:assert/strict"); var fs = require("node:fs/promises"); var os = require("node:os"); var path = require("node:path"); var test = require("node:test");
var createLeadService = require("../lib/lead-service").createLeadService; var validate = require("../lib/lead-service").validate; var adapters = require("../lib/adapters");
async function service(options) { var dir = await fs.mkdtemp(path.join(os.tmpdir(), "vg-form-")); return { store: path.join(dir, "leads.jsonl"), instance: createLeadService(Object.assign({ storePath: path.join(dir, "leads.jsonl"), adapters: [] }, options)) }; }
var form = { name: "Ava", phone: "+1 (305) 555-0100", email: "ava@example.com", address: "123 Print St", business: "Ava Co", interest: "Flyers" };
test("uses the ordered lead schema and assigns Mike", async function () { var s = await service(); var r = await s.instance.submit(form, { source: "test", clientKey: "a" }); assert.equal(r.statusCode, 202); assert.deepEqual(Object.keys(r.lead).slice(0, 10), ["id", "receivedAt", "owner", "name", "phone", "email", "address", "business", "interest", "source"]); assert.equal(r.lead.owner, "Mike"); });
test("idempotency and 24-hour contact dedupe do not create another lead", async function () { var s = await service(); var first = await s.instance.submit(Object.assign({}, form, { idempotencyKey: "abc" }), { clientKey: "a" }); var idem = await s.instance.submit(Object.assign({}, form, { idempotencyKey: "abc" }), { clientKey: "a" }); var duplicate = await s.instance.submit(Object.assign({}, form, { idempotencyKey: "different" }), { clientKey: "a" }); assert.equal(first.statusCode, 202); assert.equal(idem.statusCode, 200); assert.equal(duplicate.statusCode, 200); assert.equal((await fs.readFile(s.store, "utf8")).trim().split("\n").filter(function (x) { return !JSON.parse(x).type; }).length, 1); });
test("honeypot is accepted without persistence and rate limiting rejects excess", async function () { var s = await service({ rateLimit: { max: 1, windowMs: 60000 } }); var bot = await s.instance.submit(Object.assign({}, form, { website: "https://bot.example" }), { clientKey: "bot" }); assert.equal(bot.suppressed, "HONEYPOT"); var one = await s.instance.submit(form, { clientKey: "a" }); var two = await s.instance.submit(Object.assign({}, form, { email: "other@example.com" }), { clientKey: "a" }); assert.equal(one.statusCode, 202); assert.equal(two.statusCode, 429); });
test("generic adapters remain BLOCKED without configuration and never simulate success", async function () { var crm = adapters.createCrmAdapter({}, fetch); var email = adapters.createFlyerEmailAdapter({}, fetch); assert.equal((await crm.deliver({})).status, "BLOCKED"); assert.equal((await email.deliver({})).status, "BLOCKED"); });
test("rejects an incomplete or invalid lead", function () { assert.equal(validate({ name: "", email: "wrong" }).errors.length, 2); });
