(function (root) {
  "use strict";

  var COPY = {
    en: {
      title: "Print request",
      lead: "Tell us the job. A Vral Graphics representative reviews it before price and production.",
      leadShort: "Pick it. Add the essentials. We confirm the rest.",
      detailsQ: "A few details.",
      optional: "optional",
      notesShortPh: "Finish, date, or anything we should know.",
      contactLead: "We only use this to confirm your print request.",
      stepOf: "Step {n} of {total}",
      productQ: "What do you need?",
      productOnce: "Pick one. You can change notes later.",
      jobQ: "What is this for, and about how many?",
      goal: "What should this print do?",
      goalPh: "New clinic opening, lunch special, storefront, team cards…",
      qty: "Approximate quantity",
      qtyPh: "1000",
      specsQ: "Any specs we should lock?",
      size: "Size",
      sides: "Sides",
      sidesFront: "Front only",
      sidesTwo: "Two sides",
      design: "Design",
      designFront: "Front — $75",
      designBoth: "Front + back — $85",
      folding: "Folding",
      foldNone: "No fold",
      foldHalf: "Half fold",
      foldTri: "Tri-fold",
      foldFree: "Folding included (8.5 × 11)",
      width: "Width",
      height: "Height",
      units: "inches",
      install: "Installation",
      installYes: "Yes, install it",
      installNo: "No, pickup only",
      notes: "Notes",
      notesPh: "Paper, finish, colors, anything the press should know.",
      skipSpecs: "No extra specs yet. Continue.",
      artQ: "Where is the artwork?",
      artReady: "Ready to print",
      artAdjust: "Needs adjustment",
      artVral: "Vral should design it",
      artUnsure: "Not sure yet",
      file: "File on this device (optional)",
      fileNone: "No file selected.",
      fileSelected: "Selected on this device: {name}. Not stored yet.",
      fileStored: "File stored with request {id}.",
      fileFailed: "The file stayed on this device. It was not stored.",
      timeQ: "When do you need it, and how should it arrive?",
      timing: "Timing",
      timeStandard: "Standard — confirm days with us",
      timeDate: "I have a date",
      neededBy: "Needed by",
      fulfill: "Pickup or delivery",
      pickup: "Pickup",
      delivery: "Delivery",
      address: "Address",
      addressPh: "Street, city, ZIP",
      contactQ: "How do we reach you?",
      name: "Your name",
      business: "Business",
      phone: "Phone / WhatsApp",
      email: "Email",
      langPref: "Preferred language",
      consentContact: "Vral Graphics may contact me about this print request.",
      consentOffers: "You may send me current print offers. Optional.",
      reviewQ: "Check this ticket, then send it.",
      send: "Send print request",
      next: "Continue",
      back: "Back",
      change: "Change",
      success: "Your print request is in. A Vral Graphics representative will review the details before confirming price and production.",
      savedTitle: "Saved.",
      uploadAfter: "Add artwork after saving",
      upload: "Upload artwork",
      uploading: "Uploading…",
      continuePayment: "Continue to secure payment",
      backHome: "Back to Vral Graphics",
      fallbackTitle: "Let’s finish on WhatsApp.",
      fallback: "We could not send this from the page. The non-personal notes stayed on this device. Message us on WhatsApp.",
      wa: "Message Vral on WhatsApp",
      another: "Start another request",
      ticket: "Job ticket",
      emptyTicket: "Nothing on the ticket yet.",
      err_need_product: "Pick what you need.",
      err_need_goal: "Say what this print is for.",
      err_need_qty: "Add an approximate quantity.",
      err_need_measure: "Add width and height.",
      err_need_artwork: "Tell us about the artwork.",
      err_need_timing: "Pick a timing.",
      err_need_fulfillment: "Pick pickup or delivery.",
      err_need_address: "Add an address for delivery or install.",
      err_need_name: "Add your name.",
      err_need_business: "Add the business name.",
      err_need_phone: "Add a phone or WhatsApp number.",
      err_need_email: "Add an email.",
      err_bad_email: "That email looks incomplete.",
      err_bad_phone: "That phone looks incomplete.",
      err_need_consent: "Contact consent is required to send this request."
    },
    es: {
      title: "Pedido de impresión",
      lead: "Cuéntanos el trabajo. Una persona de Vral Graphics lo revisa antes del precio y la producción.",
      leadShort: "Elige. Agrega lo esencial. Confirmamos el resto.",
      detailsQ: "Unos detalles.",
      optional: "opcional",
      notesShortPh: "Acabado, fecha o algo que debamos saber.",
      contactLead: "Solo usamos estos datos para confirmar tu pedido.",
      stepOf: "Paso {n} de {total}",
      productQ: "¿Qué necesitas?",
      productOnce: "Elige una. Luego puedes cambiar las notas.",
      jobQ: "¿Para qué es, y más o menos cuántas?",
      goal: "¿Qué debe lograr este impreso?",
      goalPh: "Apertura de clínica, especial del día, vitrina, tarjetas del equipo…",
      qty: "Cantidad aproximada",
      qtyPh: "1000",
      specsQ: "¿Alguna especificación para cerrar?",
      size: "Tamaño",
      sides: "Caras",
      sidesFront: "Solo frente",
      sidesTwo: "Dos caras",
      design: "Diseño",
      designFront: "Frente — $75",
      designBoth: "Frente + reverso — $85",
      folding: "Doblez",
      foldNone: "Sin doblez",
      foldHalf: "Mitad",
      foldTri: "Tríptico",
      foldFree: "Doblez incluido (8.5 × 11)",
      width: "Ancho",
      height: "Alto",
      units: "pulgadas",
      install: "Instalación",
      installYes: "Sí, instálenlo",
      installNo: "No, solo recojo",
      notes: "Notas",
      notesPh: "Papel, acabado, colores, lo que la prensa deba saber.",
      skipSpecs: "Sin extras por ahora. Seguir.",
      artQ: "¿Dónde está el arte?",
      artReady: "Listo para imprimir",
      artAdjust: "Necesita ajuste",
      artVral: "Que Vral lo diseñe",
      artUnsure: "Aún no sé",
      file: "Archivo en este aparato (opcional)",
      fileNone: "No hay archivo.",
      fileSelected: "Elegido en este aparato: {name}. Aún no está guardado.",
      fileStored: "Archivo guardado con el pedido {id}.",
      fileFailed: "El archivo se quedó en este aparato. No se guardó.",
      timeQ: "¿Para cuándo, y cómo llega?",
      timing: "Tiempo",
      timeStandard: "Estándar — confirmamos los días",
      timeDate: "Tengo una fecha",
      neededBy: "Se necesita para",
      fulfill: "Recoger o entrega",
      pickup: "Recoger",
      delivery: "Entrega",
      address: "Dirección",
      addressPh: "Calle, ciudad, ZIP",
      contactQ: "¿Cómo te localizamos?",
      name: "Tu nombre",
      business: "Negocio",
      phone: "Teléfono / WhatsApp",
      email: "Correo",
      langPref: "Idioma preferido",
      consentContact: "Vral Graphics puede contactarme sobre este pedido de impresión.",
      consentOffers: "Pueden enviarme ofertas de impresión. Opcional.",
      reviewQ: "Revisa esta orden y envíala.",
      send: "Enviar pedido de impresión",
      next: "Seguir",
      back: "Atrás",
      change: "Cambiar",
      success: "Tu pedido de impresión llegó. Un representante de Vral Graphics revisará los detalles antes de confirmar precio y producción.",
      savedTitle: "Guardado.",
      uploadAfter: "Agrega el arte después de guardar",
      upload: "Subir arte",
      uploading: "Subiendo…",
      continuePayment: "Continuar al pago seguro",
      backHome: "Volver a Vral Graphics",
      fallbackTitle: "Terminemos por WhatsApp.",
      fallback: "No pudimos enviar esto desde la página. Las notas que no son personales se quedaron en este aparato. Escríbenos por WhatsApp.",
      wa: "Escribir a Vral por WhatsApp",
      another: "Empezar otro pedido",
      ticket: "Orden de trabajo",
      emptyTicket: "La orden aún está vacía.",
      err_need_product: "Elige lo que necesitas.",
      err_need_goal: "Di para qué es este impreso.",
      err_need_qty: "Pon una cantidad aproximada.",
      err_need_measure: "Pon ancho y alto.",
      err_need_artwork: "Cuéntanos del arte.",
      err_need_timing: "Elige un tiempo.",
      err_need_fulfillment: "Elige recoger o entrega.",
      err_need_address: "Pon una dirección para entrega o instalación.",
      err_need_name: "Pon tu nombre.",
      err_need_business: "Pon el nombre del negocio.",
      err_need_phone: "Pon un teléfono o WhatsApp.",
      err_need_email: "Pon un correo.",
      err_bad_email: "Ese correo se ve incompleto.",
      err_bad_phone: "Ese teléfono se ve incompleto.",
      err_need_consent: "El consentimiento de contacto es necesario para enviar este pedido."
    }
  };

  function lang() {
    try {
      if (root.VralSite && typeof root.VralSite.lang === "function") return root.VralSite.lang();
      return localStorage.getItem("vral-lang") === "es" ? "es" : "en";
    } catch (err) {
      return "en";
    }
  }

  function t(key, vars) {
    var table = COPY[lang()] || COPY.en;
    var text = table[key] || COPY.en[key] || key;
    vars = vars || {};
    return text.replace(/\{(\w+)\}/g, function (_, name) {
      return vars[name] == null ? "" : String(vars[name]);
    });
  }

  root.VralQuoteCopy = { COPY: COPY, t: t, lang: lang };
})(typeof window !== "undefined" ? window : globalThis);
